<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained Condition="'$(SelfContained)'==''">true</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
